"""make_layout.py -- write layout.md by serializing instances with Waveflow.

    python make_layout.py

Nothing here reasons about the schema.  For each message and each word width it serializes
an instance with one field set to all ones (everything else zero) and records which bits of
which word came out set; then it serializes one example instance and prints its words.
Sample bursts go through ``write_array``.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from fir import (
    WORD_BW_SUPPORTED, FirCmdHdr, FirError, FirRespFtr, FirRespHdr, FirStatusMsg, Int16,
)
from waveflow.hw.arrayutils import write_array

MESSAGES = [
    (FirCmdHdr, "Command header (`CmdHdr`)",
     {"tx_id": 0x1234, "opcode": 2, "count": 1000, "decim": 4, "reset": 1}),
    (FirRespHdr, "Response header (`RespHdr`)", {"tx_id": 0x1234, "opcode": 2}),
    (FirRespFtr, "Response footer (`RespFtr`)", {"nin": 1000, "nout": 250, "error": FirError.NO_TLAST}),
    (FirStatusMsg, "Status message (`StatusMsg`)",
     {"ntaps": 32, "nsamp_total": 0x89ABCDEF, "nerr": 3, "last_error": FirError.BAD_DECIM}),
]


def _ones(cls, name):
    """The largest value the field holds, found by trying widths through serialization."""
    inst = cls()
    for bits in range(64, 0, -1):
        try:
            setattr(inst, name, (1 << bits) - 1)
            inst.serialize(word_bw=64)
            return (1 << bits) - 1
        except Exception:
            continue
    raise RuntimeError(f"{cls.__name__}.{name}: no value serializes")


def _set_bits(words):
    res = []
    for wi, w in enumerate(int(v) for v in words):
        bits = [b for b in range(64) if (w >> b) & 1]
        if bits:
            res.append((wi, min(bits), max(bits)))
    return res


def _type_name(cls, name):
    sch = cls.elements[name]["schema"]
    bw = getattr(sch, "bitwidth", None)
    signed = getattr(sch, "signed", False)
    if hasattr(sch, "enum_type"):
        return f"enum {sch.enum_type.__name__}"
    return f"{'i' if signed else 'u'}{bw}"


def message_tables(cls, title, example) -> list[str]:
    out = [f"## {title}", ""]
    for bw in WORD_BW_SUPPORTED:
        nwords = cls().serialize(word_bw=bw).size
        out += [f"**{bw}-bit words** ({nwords} word{'s' if nwords > 1 else ''}, TLAST on the last)", "",
                "| Word | Bits | Field | Type |", "| --- | --- | --- | --- |"]
        for name in cls.elements:
            inst = cls()
            setattr(inst, name, _ones(cls, name) if "error" not in name else max(FirError))
            if "error" in name:
                # an enum: set every bit the encoding can hold by OR-ing all codes' patterns
                pats = []
                for e in FirError:
                    i2 = cls(); setattr(i2, name, e); pats.append(i2.serialize(word_bw=bw))
                words = np.bitwise_or.reduce(np.array(pats, dtype=np.uint64), axis=0)
            else:
                words = inst.serialize(word_bw=bw)
            for wi, lo, hi in _set_bits(words):
                out.append(f"| {wi} | {hi}:{lo} | `{name}` | {_type_name(cls, name)} |")
        ex = cls()
        for k, v in example.items():
            setattr(ex, k, v)
        ws = ex.serialize(word_bw=bw)
        hexw = ", ".join(f"0x{int(w):0{bw // 4}x}" for w in ws)
        out += ["", f"Example {example} serializes to `[{hexw}]`.", ""]
    return out


def sample_tables() -> list[str]:
    out = ["## Sample, tap and output bursts (`h[...]`, `x[...]`, `y[...]`)", "",
           "Q1.15 values as `i16`, through `write_array(..., elem_type=Int16)`.  Example: "
           "the five values `[1, -2, 3, -4, 5]` (an odd count, so the last word is partial):", ""]
    vals = np.array([1, -2, 3, -4, 5], dtype=np.int16)
    for bw in WORD_BW_SUPPORTED:
        ws = write_array(vals, elem_type=Int16, word_bw=bw)
        hexw = ", ".join(f"0x{int(w):0{bw // 4}x}" for w in ws)
        out += [f"**{bw}-bit words**: {bw // 16} values per word, value `i` in bits "
                f"`[16*(i mod {bw // 16})+15 : 16*(i mod {bw // 16})]` of word `i div {bw // 16}`; "
                f"`[1, -2, 3, -4, 5]` -> `[{hexw}]`.", ""]
        out += ["| Word | Bits | Value index |", "| --- | --- | --- |"]
        for i in range(bw // 16):
            one = np.zeros(bw // 16, dtype=np.int16)
            one[i] = -1
            for wi, lo, hi in _set_bits(write_array(one, elem_type=Int16, word_bw=bw)):
                out.append(f"| k | {hi}:{lo} | {bw // 16}k + {i} |")
        out.append("")
    out += ["Unused lanes of a final partial word are written as zero (the example's last "
            "word above) and ignored on input.  A burst carries `ceil(n / (W/16))` words, "
            "TLAST on the last.", ""]
    return out


def main() -> None:
    lines = ["# Wire layout", "",
             "Generated by `python make_layout.py`: every row comes from serializing an "
             "instance with Waveflow (one field set to all ones), not from reading the schema.",
             "Every `|` in the protocol table of the spec is a TLAST: each message below is "
             "one burst.", ""]
    for cls, title, example in MESSAGES:
        lines += message_tables(cls, title, example)
    lines += sample_tables()
    path = Path(__file__).resolve().parent / "layout.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
